const trips={balanced:{title:'Option 1 — Balanced',tag:'The Classic Journey',route:'Direct Nullarbor both ways with maximum Adelaide time.',meta:['18 days','~5,600 km','12 driving days'],outbound:[['Day 1','Perth → Southern Cross','373 km','4h20','Southern Cross Motel / cabin'],['Day 2','Southern Cross → Balladonia','570 km','5h50','Balladonia Hotel Motel'],['Day 3','Balladonia → Eucla','492 km','5h00','Eucla Motor Hotel'],['Day 4','Eucla → Ceduna','491 km','5h00','Ceduna Foreshore / Tourist Park'],['Day 5','Ceduna → Port Augusta','468 km','4h50','Majestic Oasis / family motel'],['Day 6','Port Augusta → Adelaide','310 km','3h30','Adelaide stay']],return:[['Day 12','Adelaide → Port Augusta','310 km','3h30','Port Augusta'],['Day 13','Port Augusta → Ceduna','468 km','4h50','Ceduna'],['Day 14','Ceduna → Eucla','491 km','5h00','Eucla'],['Day 15','Eucla → Balladonia','492 km','5h00','Balladonia'],['Day 16','Balladonia → Southern Cross','570 km','5h50','Southern Cross'],['Day 17','Southern Cross → Perth','373 km','4h20','Home'],['Day 18','Buffer / recovery day','—','—','Contingency']]},wa:{title:'Option 2 — Scenic WA',tag:'The Coastal Detour',route:'Esperance and Lucky Bay outbound, then direct return.',meta:['18 days','~5,900 km','13 driving days'],outbound:[['Day 1','Perth → Albany / Ravensthorpe corridor','~500 km','5–6h','Family stop'],['Day 2','Continue → Esperance','~300 km','3–4h','Esperance'],['Day 3','Esperance + Lucky Bay','Local','Easy day','Esperance'],['Day 4','Esperance → Norseman / Balladonia','~390 km','4–5h','Balladonia'],['Day 5','Balladonia → Eucla','492 km','5h00','Eucla'],['Day 6','Eucla → Ceduna','491 km','5h00','Ceduna'],['Day 7','Ceduna → Port Augusta','468 km','4h50','Port Augusta'],['Day 8','Port Augusta → Adelaide','310 km','3h30','Adelaide']],return:[['Return','Adelaide → Perth','Direct Nullarbor','6 driving days','Same core stops as Balanced']]},sa:{title:'Option 3 — Scenic SA',tag:'The Eyre Peninsula Loop',route:'Direct outbound, scenic return via Port Lincoln, Coffin Bay and Streaky Bay.',meta:['18 days','~6,200 km','13 driving days'],outbound:[['Day 1','Perth → Southern Cross','373 km','4h20','Southern Cross'],['Day 2','Southern Cross → Balladonia','570 km','5h50','Balladonia'],['Day 3','Balladonia → Eucla','492 km','5h00','Eucla'],['Day 4','Eucla → Ceduna','491 km','5h00','Ceduna'],['Day 5','Ceduna → Port Augusta','468 km','4h50','Port Augusta'],['Day 6','Port Augusta → Adelaide','310 km','3h30','Adelaide']],return:[['Scenic 1','Adelaide → Port Lincoln','Eyre Peninsula','5–6h','Port Lincoln'],['Scenic 2','Coffin Bay + coast','Local','Easy day','Port Lincoln / Coffin Bay'],['Scenic 3','Port Lincoln → Streaky Bay','~380 km','4–5h','Streaky Bay'],['Scenic 4','Streaky Bay → Eucla','~620 km','6h+','Needs refinement'],['Then','Eucla → Perth','Direct Nullarbor','3 driving days','Core WA stops']]}};

let selected='balanced',showReturn=false;
const optionGrid=document.getElementById('optionGrid');
const itineraryTitle=document.getElementById('itineraryTitle');
const itineraryList=document.getElementById('itineraryList');
const toggleReturn=document.getElementById('toggleReturn');
const feedbackStatus=document.getElementById('feedbackStatus');

function renderOptions(){optionGrid.innerHTML='';Object.entries(trips).forEach(([key,t],i)=>{const card=document.createElement('article');card.className='option-card'+(key===selected?' selected':'');card.innerHTML=`<div class="option-number">OPTION ${i+1}</div><h3>${t.title.replace(/^Option \d — /,'')}</h3><div class="option-tag">${t.tag}</div><div class="option-route">${t.route}</div><div class="option-meta">${t.meta.map(m=>`<span>${m}</span>`).join('')}</div>`;card.addEventListener('click',()=>{selected=key;showReturn=false;renderAll();document.getElementById('itineraryTitle').scrollIntoView({behavior:'smooth',block:'center'});});optionGrid.appendChild(card);});}
function renderItinerary(){const t=trips[selected];itineraryTitle.textContent=t.title;const days=showReturn?t.return:t.outbound;itineraryList.innerHTML=days.map(d=>`<article class="day-card"><div class="day-index">${d[0]}</div><div><h4>${d[1]}</h4><p>Suggested stay: ${d[4]}</p></div><div class="day-km"><b>${d[2]}</b>${d[3]}</div></article>`).join('');toggleReturn.textContent=showReturn?'Show Outbound':'Show Return';}
function renderVote(){const votes=JSON.parse(localStorage.getItem('royalRoadVotes')||'{}');document.querySelectorAll('[data-vote]').forEach(b=>b.classList.toggle('active',votes[selected]===b.dataset.vote));feedbackStatus.textContent=votes[selected]?`Saved: ${votes[selected][0].toUpperCase()+votes[selected].slice(1)} for ${trips[selected].title}.`:'No vote saved on this device yet.';}
function renderAll(){renderOptions();renderItinerary();renderVote();}
toggleReturn.addEventListener('click',()=>{showReturn=!showReturn;renderItinerary();});
document.querySelectorAll('[data-vote]').forEach(b=>b.addEventListener('click',()=>{const votes=JSON.parse(localStorage.getItem('royalRoadVotes')||'{}');votes[selected]=b.dataset.vote;localStorage.setItem('royalRoadVotes',JSON.stringify(votes));renderVote();}));

const noteForm=document.getElementById('noteForm'),noteList=document.getElementById('noteList');
function getNotes(){return JSON.parse(localStorage.getItem('royalRoadNotes')||'[]');}
function renderNotes(){const notes=getNotes();noteList.innerHTML=notes.length?notes.slice().reverse().slice(0,6).map(n=>`<div class="note-item"><b>${escapeHtml(n.name)} · ${escapeHtml(n.option)}</b><p>${escapeHtml(n.text)}</p></div>`).join(''):'<p class="muted">No notes yet on this device.</p>';}
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
noteForm.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('noteName').value.trim(),text=document.getElementById('noteText').value.trim();if(!name||!text)return;const notes=getNotes();notes.push({name,text,option:trips[selected].title,createdAt:new Date().toISOString()});localStorage.setItem('royalRoadNotes',JSON.stringify(notes));noteForm.reset();renderNotes();});

renderAll();renderNotes();